# Site settings
title: Chiao
email: chiaoy@sjtu.edu.cn

description: > # this means to ignore newlines until "baseurl:"
  Fly. Study. Fly.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "chiaoy.github.io" # the base hostname & protocol for your site
facebook_username: chiaoy
github_username:  ChiaoY

# Build settings
markdown: kramdown
